[project]
name = "sorapy-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Zora_", email = "rayyt2551@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
sorapy-bot = "sorapy_bot:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
